{{- $chartName := include "tiles-splitter.name" . -}}
{{- $tracingUrl := include "tiles-splitter.tracingUrl" . -}}
{{- $metricsUrl := include "tiles-splitter.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  SPLIT_ATTEMPTS: {{ .Values.env.splitAttempts | quote }}
  TILES_PATH: {{ .Values.env.tiles.path | quote }}
  QUEUE_JOB_MANAGER_BASE_URL: {{ .Values.env.queue.jobManagerBaseUrl | quote }}
  QUEUE_HEART_BEAT_MANAGER_BASE_URL: {{ .Values.env.queue.heartbeatIntervalMs | quote }}
  QUEUE_DEQUEUE_INTERVAL_MS: {{ .Values.env.queue.dequeueIntervalMs | quote }}
  QUEUE_HEART_BEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeatManagerBaseUrl | quote }}
  QUEUE_JOB_TYPE: {{ .Values.env.queue.jobType | quote }}
  QUEUE_SPLIT_TILES_TASK_TYPE: {{ .Values.env.queue.splitTilesTaskType | quote }}
  STORAGE_PROVIDER: {{ .Values.env.storageProvider | quote }}
  S3_ENDPOINT: {{ .Values.env.S3.endpoint | quote }}
  S3_BUCKET: {{ .Values.env.S3.bucket | quote }}
  S3_FORCE_PATH_STYLE: {{ .Values.env.S3.forcePathStyle | quote }}
{{- end }}
