{{- $chartName := include "tiles-splitter.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracingUrl := include "tiles-splitter.tracingUrl" . -}}
{{- $metricsUrl := include "tiles-splitter.metricsUrl" . -}}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $jobManagement := (include "common.jobManagement.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  SPLIT_ATTEMPTS: {{ .Values.env.splitAttempts | quote }}
  SOURCE_MOUNT_PATH: "/layerSources"
  {{ if eq (upper $storage.tilesStorageProvider) "FS" }}
  TILES_PATH: "/app/tiles_outputs"
  {{ end }}
  VRT_OUTPUT_DIR_PATH: "/app/vrtOutputs"
  VRT_SOURCES_LIST_FILE_PATH: "/app/vrtOutputs/files.txt"
  VRT_NODATA: {{ .Values.env.vrt.nodata | quote}}
  VRT_OUTPUT_SRS: {{ .Values.env.vrt.outputSRS | quote }}
  VRT_RESAMPLING: {{ .Values.env.vrt.resampling | quote }}
  VRT_ADD_ALPHA: {{ .Values.env.vrt.addAlpha | quote }}
  VRT_USE_BAND_COUNT: {{ .Values.env.vrt.useBandCount | quote }}
  VRT_INPUT_BAND_COUNT: {{ .Values.env.vrt.inputBandCount | quote }}
  GENERATE_TILES_RESMAPLING: {{ .Values.env.generateTiles.resampling | quote }}
  GENERATE_TILES_PROFILE: {{ .Values.env.generateTiles.profile | quote }}
  GENERATE_TILES_SRC_NODATA: {{ .Values.env.generateTiles.srcnodata | quote }}
  GENERATE_TILES_VERBOSE: {{ .Values.env.generateTiles.verbose | quote }}
  QUEUE_JOB_MANAGER_BASE_URL: {{ $serviceUrls.jobManager | quote }}
  QUEUE_HEART_BEAT_MANAGER_BASE_URL: {{ $serviceUrls.heartbeatManager | quote }}
  QUEUE_DEQUEUE_INTERVAL_MS: {{ .Values.env.queue.dequeueIntervalMs | quote }}
  QUEUE_HEART_BEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeatIntervalMs | quote }}
  QUEUE_JOB_TYPE: {{ $jobManagement.ingestion.new.jobType | quote }}
  QUEUE_TASK_TYPE: {{ $jobManagement.ingestion.new.splitTilesTaskType | quote }}
  STORAGE_PROVIDER: {{ $storage.tilesStorageProvider | quote }}
  AWS_S3_ENDPOINT: {{ $s3.endpointUrl | quote }}
  S3_BUCKET: {{ $s3.tilesBucket | quote }}
  S3_FORCE_PATH_STYLE: {{ $s3.forcePathStyle | quote }}
  AWS_HTTPS: {{ $s3.sslEnabled | quote }}
  AWS_VIRTUAL_HOSTING: {{ $s3.virtualHosting | quote }}
  DISCRETE_OVERSEER_URL: {{ $serviceUrls.discreteOverseer | quote }}
{{- end }}
