{{- $releaseName := .Release.Name -}}
{{- $chartName := include "tiles-splitter.name" . -}}
{{- $cloudProviderFlavor := include "tiles-splitter.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "tiles-splitter.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "tiles-splitter.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "tiles-splitter.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "tiles-splitter.environment" . }}
    release: {{ $releaseName }}
    {{- include "tiles-splitter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "tiles-splitter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "tiles-splitter.selectorLabels" . | nindent 8 }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
      - name: ingestion-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.ingestionSourcePvc.name }}
    {{- if eq (upper .Values.env.storageProvider) "FS" }}
      - name: tiles-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.internalPvc.name }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if eq (upper .Values.env.storageProvider) "S3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.S3.secret.name }}
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.S3.secret.name }}
                  key: secretAccessKey
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          volumeMounts:
            - name: ingestion-storage
              mountPath: /layerSources
            {{- if eq (upper .Values.env.storageProvider) "FS" }}
            - name: tiles-storage
              mountPath: /app/tiles_outputs
              subPath: tiles
            {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
         {{- end }}
{{- end -}}
