{{- $releaseName := .Release.Name -}}
{{- $chartName := include "tiles-splitter.name" . -}}
{{- $cloudProviderFlavor := include "tiles-splitter.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "tiles-splitter.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "tiles-splitter.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "tiles-splitter.tag" . -}}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $deploymentName := include "deployment.fullname" . }}
{{- $configmapName := include "configmap.fullname" . }}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
{{- $fs := (include "common.fs.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "tiles-splitter.environment" . }}
    release: {{ $releaseName }}
    {{- include "tiles-splitter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "tiles-splitter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "tiles-splitter.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.useNodeAffinity }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: nodeAffinity
                operator: In
                values:
                - nodeAffinityPod
            topologyKey: kubernetes.io/hostname
      {{- end }}
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
      - name: ingestion-storage
        persistentVolumeClaim:
          claimName: {{ $fs.ingestionSourcePvc.name }}
    {{- if eq (upper $storage.tilesStorageProvider) "FS" }}
      - name: tiles-storage
        persistentVolumeClaim:
          claimName: {{ $fs.internalPvc.name }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if eq (upper $storage.tilesStorageProvider) "S3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $s3.secretName }}
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $s3.secretName }}
                  key: secretAccessKey
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $configmapName }}
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          volumeMounts:
            - name: ingestion-storage
              mountPath: /layerSources
              {{- if $fs.ingestionSourcePvc.subPath }}
              subPath: {{ $fs.ingestionSourcePvc.subPath }}
              {{- end }}
            {{- if eq (upper $storage.tilesStorageProvider) "FS" }}
            - name: tiles-storage
              mountPath: /app/tiles_outputs
              subPath: {{ $fs.internalPvc.tilesSubPath }}
            {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
         {{- end }}
{{- end -}}
