{{- if and (eq (upper .Values.rasterCommon.storage.tilesStorageProvider) "FS") .Values.storage.internalPvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rasterCommon.storage.fs.tilesPvc.name }}
  labels:
    app: "tiles-splitter"
    component: "tiles-splitter"
    environment: "development"
spec:
  storageClassName: host-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end -}}
