{{- if and (eq (upper .Values.env.storageProvider) "S3") .Values.env.S3.secret.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.S3.secret.name }}
type: Opaque
stringData:
  accessKeyId: {{ quote .Values.env.S3.secret.accessKeyId }}
  secretAccessKey: {{ quote .Values.env.S3.secret.secretAccessKey }}
{{- end }}
