{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
{{- if and (eq (upper $storage.tilesStorageProvider) "S3") .Values.S3.secret.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s3.secretName }}
type: Opaque
stringData:
  accessKeyId: {{ quote .Values.S3.secret.accessKeyId }}
  secretAccessKey: {{ quote .Values.S3.secret.secretAccessKey }}
{{- end }}
