{{- if and (eq (upper .Values.rasterCommon.storage.tilesStorageProvider) "S3") .Values.S3.secret.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rasterCommon.storage.S3.secretName }}
type: Opaque
stringData:
  accessKeyId: {{ quote .Values.S3.secret.accessKeyId }}
  secretAccessKey: {{ quote .Values.S3.secret.secretAccessKey }}
{{- end }}
